version: "3"

services:
  postgres:
    image: postgres:13
    
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
     - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  server:
    build: ./server
    platform: linux/amd64
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:example@postgres:5432/mydb
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./server:/app
    command: ["air"]
  
  client:
    build: ./client
    platform: linux/amd64
    depends_on:
      - server
    ports:
      - "5173:5173"
    environment:
      VITE_SERVER_URL: http://localhost:3000
      VITE_AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      VITE_AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./client:/app
    command: sh -c "npm rebuild esbuild && yarn dev"