# Set the base image to use
FROM golang:1.16-alpine3.13

# Set the working directory
WORKDIR /app

# Copy the source code to the working directory
COPY . .

# Install the necessary packages
RUN go get -d -v ./...
RUN go install -v ./...

# Expose the port that the server listens on
EXPOSE 8080

# Start the server
CMD ["./app"]