FROM golang:1.20 as base

FROM base as dev

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod tidy

COPY . .
CMD ["air",]